local: &local  
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
development: *local  
test: *local  

production: &production
  :url: <%= ENV['REDISTOGO_URL'] %>
  :host: <%= ENV['REDIS_HOST'] %>
  :password: <%= ENV['REDIS_PASSWORD'] %>
  :inline: true
  :timeout: 1